### ISSUE TITLE
работа countingSort

### ISSUE THREAD

**Issue by Tka4uk-Andrei** [svaflica/Algorithms#2]
За что отвечает переменная lengthSort? 
`int lengthSort = max(array, length);`
Разве max (у меня он красный) будет без algorithms работать?
В чём смысл сравнивать указатель и длину?

**Comment by Tka4uk-Andrei** [comment]
Я тупой. Не заметил max. Его надо поместить выше countingSort

**Comment by svaflica** [comment]
А почему выше?

**Comment by svaflica** [comment]
(У меня все компилится)

**Comment by Tka4uk-Andrei** [comment]
у меня, увы, нет.
Выше потому что max не видит моя VS
