### ISSUE TITLE
Объявление функций в заголовках

### ISSUE THREAD

**Issue by Tka4uk-Andrei** [svaflica/Algorithms#3]
Для шаблонных функций не надо писать заголовки
http://qaru.site/questions/1162/why-can-templates-only-be-implemented-in-the-header-file

**Comment by svaflica** [comment]
Без заголовков появляется ошибка

**Comment by Tka4uk-Andrei** [comment]
В заголовке надо написать тело функции

**Comment by svaflica** [comment]
Она же тесты смотреть не будет?
