### ISSUE TITLE
CountSort и отрицательные числа

### ISSUE THREAD

**Issue by Tka4uk-Andrei** [svaflica/Algorithms#9]
Можно ли расширить его для работы с неотрицательными числами

**Comment by svaflica** [comment]
Думаю, нужно найти минимальное и максимальное числа, а потом создать массив, в котором количество элементов есть сумма мин и макс с прибавленной единицей, а, значит, нулевой элемент будет обозначать минимальный элемент, 1 - следующий по старшенству после минимального и т.д.

**Comment by svaflica** [comment]
Мне так кажется

**Comment by Tka4uk-Andrei** [comment]
Улучшишь тогда?
